### ISSUE TITLE
Añadir estadísticas de productos

### ISSUE THREAD

**Issue by uo271080** [Arquisoft/dede_es1b#184]
- Se añadirá al producto el cambio número de ventas.
- Se calcularán las ganancias totales multiplicando el número de ventas por el precio del producto
- Se mostrarán estos valores en una ventana de estadísticas específica para cada producto

**Comment by UO277646** [comment]
Estan añadidas pero no se utilizan , se utilizan en un futuro de la aplicacion :persevere:
