### ISSUE TITLE
Bocetos de pantallas

### ISSUE THREAD

**Issue by UO277303** [Arquisoft/dede_es1b#59]
Crear unos primeros bocetos para las pantallas de la aplicación.

**Comment by uo271080** [comment]
Los bocetos son los siguientes:

* **VENTANA BIENVENIDA:**

![ventanaBienvenida](https://user-images.githubusercontent.com/60232864/156219659-7681e872-b305-4a50-8ee7-cd5a4cc361f8.png)

* **VENTANA INICIO:**

![ventanaInicio](https://user-images.githubusercontent.com/60232864/156219715-a543ef30-aa93-47b2-a4b0-8f0628ca8e63.png)


* **VENTANA INICIO SESIÓN:**

![ventanaInicioSesion](https://user-images.githubusercontent.com/60232864/156219740-29f5288b-4c99-4006-9d71-e7ce133dfce3.png)

* **VENTANA REGISTRO:**

![ventanaRegistro](https://user-images.githubusercontent.com/60232864/156219643-bb4cb9f5-b040-4038-b6b5-74f0974f93ef.png)
